### ISSUE TITLE
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by droopanu** [haggis663/ha-melview#4]
Error loading the integration in 2023.05.0

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/melview/__init__.py:93
Integration: MelView (documentation, issues)
First occurred: 10:33:48 AM (3 occurrences)
Last logged: 11:22:53 AM

Error setting up entry xxxxx@gmail.com for melview
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/melview/__init__.py", line 93, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

Logger: homeassistant.components.climate
Source: custom_components/melview/climate.py:355
Integration: Climate (documentation, issues)
First occurred: 10:33:52 AM (1 occurrences)
Last logged: 10:33:52 AM

Error while setting up melview platform for climate
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/melview/climate.py", line 355, in setup_platform
    email = config[DOMAIN][CONF_EMAIL]
KeyError: 'melview'

**Comment by grssll** [comment]
Same problem. Stopped working after last HA update

**Comment by haggis663** [comment]
I have updated the deprecated line to the non-deprecated version.
